### ISSUE TITLE
Error Message.

### ISSUE THREAD

**Issue by MichaelPyron** [munawarb/Three-D-Velocity#12]
Hi, I posted an issue about TDV working with windows 10, and I just want to say thanks for getting back with me..
However, I found the error I was asking about.
I am paysting the text from the error below..
Any help would be very much appreciated.
Thanks again in advance,
Michael..
The error is,

Error log, created with build version 2.23.0.29094: 
Error base exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpDX.XAudio2.MasteringVoice..ctor(XAudio2 device, Int32 inputChannels, Int32 inputSampleRate, Int32 deviceIndex)
   at BPCSharedComponent.ExtendedAudio.DSound.initializeOgg() in c:\Users\munawar\projects\Three-D-Velocity\shared\BPCSharedComponent\DSound.cs:line 132
   at TDV.GUI..ctor() in c:\Users\munawar\projects\Three-D-Velocity\TDV\GUI.cs:line 81
   at TDV.Common.Main(String[] args) in c:\Users\munawar\projects\Three-D-Velocity\TDV\Common.cs:line 238
Error Description: Object reference not set to an instance of an object.
Stack trace:    at SharpDX.XAudio2.MasteringVoice..ctor(XAudio2 device, Int32 inputChannels, Int32 inputSampleRate, Int32 deviceIndex)
   at BPCSharedComponent.ExtendedAudio.DSound.initializeOgg() in c:\Users\munawar\projects\Three-D-Velocity\shared\BPCSharedComponent\DSound.cs:line 132
   at TDV.GUI..ctor() in c:\Users\munawar\projects\Three-D-Velocity\TDV\GUI.cs:line 81
   at TDV.Common.Main(String[] args) in c:\Users\munawar\projects\Three-D-Velocity\TDV\Common.cs:line 238

**Comment by munawarb** [comment]
@MichaelPyron Please see this section on the homepage:

> # Dependencies
> TDV relies on XAudio2 for some of its sound rendering. If you don't have XAudio2 installed, you'll get a semi-cryptic message at startup with the word "xaudio2" in it. If this happens, download and run the [Microsoft DirectX Web Installer.](https://www.microsoft.com/en-us/download/details.aspx?id=35)
> Also, make sure to delete your previous configuration of TDV if you've ever had TDV on your computer, or this version might not work. You can find TDV config files in %APPDATA%\BPCPrograms
> 
> 

I'm leaving this issue open. Please follow the instructions here and let me know if it solves the problem.

**Comment by MichaelPyron** [comment]
Hi Munawarb,
 I installed direct X, and it fix the audio problem. However, there is another issue. The game does not pose properly. It takes several seconds for it to do so during gameplay. What could be the issue? Even when pressing escape, the same applies.  Thanks again for all your help.

**Comment by munawarb** [comment]
The game loads many sounds, and when it exits it has to clean up these sounds before shutting down. Otherwise, the only real way to recover the memory the game uses is to reboot your system.
