### ISSUE TITLE
TDV crashes on me

### ISSUE THREAD

**Issue by blindpilot** [munawarb/Three-D-Velocity#30]
to you munawar.
I finally got TDV to fire up on my pc by creating a tdv folder within my documents folder.
Now after the tdv program fires up and the intro has been completed, I get the following error.
Error log, created with build version 2.23.0.3664: 
Error base exception: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.DirectSound.SoundBuffer.GetStatus(Int32& tatusRef)
   at SharpDX.DirectSound.SoundBuffer.get_Status()
   at BPCSharedComponent.ExtendedAudio.DSound.isPlaying(SecondarySoundBuffer s)
   at TDV.SelfVoice.NumWait()
   at TDV.SelfVoice.NLS(String sFilename, Boolean NWait, Int64 TheRate)
Error Description: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

Stack trace:    at SharpDX.Result.CheckError()
   at SharpDX.DirectSound.SoundBuffer.GetStatus(Int32& tatusRef)
   at SharpDX.DirectSound.SoundBuffer.get_Status()
   at BPCSharedComponent.ExtendedAudio.DSound.isPlaying(SecondarySoundBuffer s)
   at TDV.SelfVoice.NumWait()
   at TDV.SelfVoice.NLS(String sFilename, Boolean NWait, Int64 TheRate)
Now I was able to open up the following zip folder to gain access to the tdv exe file to be moved to my documents folder which was the 
tdv-compiled.7z
Now how can I fix this so that the next time I fire up TDV it will not crash on me so I once again may stary enjoying TDV once again?
Very Thankfully Yours,
Ron Kolesar

**Comment by munawarb** [comment]
Hi @blindpilot,
I'm suspecting that your zip file is corrupt. Did you try to re-extract the file?
