### ISSUE TITLE
the game wont start on my pc

### ISSUE THREAD

**Issue by wiam-s** [munawarb/Three-D-Velocity#33]
I got this error while openning the game, here's the log: 
Error log, created with build version 2.1.1.35962: 
Error base exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpDX.XAudio2.MasteringVoice..ctor(XAudio2 device, Int32 inputChannels, Int32 inputSampleRate, Int32 deviceIndex)
   at BPCSharedComponent.ExtendedAudio.DSound.initializeOgg() in C:\Users\munawar\projects\Three-D-Velocity\shared\BPCSharedComponent\DSound.cs:line 132
   at TDV.GUI..ctor() in C:\Users\munawar\projects\Three-D-Velocity\TDV\GUI.cs:line 81
   at TDV.Common.Main(String[] args) in C:\Users\munawar\projects\Three-D-Velocity\TDV\Common.cs:line 238
Error Description: Object reference not set to an instance of an object.
Stack trace:    at SharpDX.XAudio2.MasteringVoice..ctor(XAudio2 device, Int32 inputChannels, Int32 inputSampleRate, Int32 deviceIndex)
   at BPCSharedComponent.ExtendedAudio.DSound.initializeOgg() in C:\Users\munawar\projects\Three-D-Velocity\shared\BPCSharedComponent\DSound.cs:line 132
   at TDV.GUI..ctor() in C:\Users\munawar\projects\Three-D-Velocity\TDV\GUI.cs:line 81
   at TDV.Common.Main(String[] args) in C:\Users\munawar\projects\Three-D-Velocity\TDV\Common.cs:line 238

**Comment by munawarb** [comment]
Hi @wiam-s,
Check out the Dependencies section and install the DirectX Web Installer from there. That will solve your issue.
